export const slidesData = [
  {
    id: 1,
    category: 'Timeless Beauty',
    title: 'JEWELRY SETS',
    highlight: 'GET UP TO 10% OFF',
    description: 'Sparkle and Save: Enjoy our stunning jewelry collection at discounted prices!',
    bgColor: 'rgba(245, 237, 230, 0.5)', 
    image: '//enovathemes.com/joice/wp-content/uploads/slide-1-asset-2-1.webp',
    link: '/shop',
    linkText: 'Shop now',
  },
  {
    id: 2,
    category: 'Modern Charm',
    title: 'ELEGANT COLLECTION',
    highlight: 'FOR YOUR LADY',
    description: "More than just an accessory, it's a reflection of your individuality.",
    bgColor: 'rgba(245, 213, 190, 0.6)', 
    image: '//enovathemes.com/joice/wp-content/uploads/slide-1-asset-4.webp',
    link: '/shop',
    linkText: 'Shop now',
  },
  {
    id: 3,
    category: 'New Collection',
    title: 'LUXURY RINGS',
    highlight: 'DISCOVER OUR',
    description: 'Experience the true beauty and unmatched craftsmanship of our exclusive ring selection.',
    bgColor: 'rgba(201, 162, 54, 0.1)', 
    image: '//enovathemes.com/joice/wp-content/uploads/slide-1-asset-3.webp',
    link: '/shop',
    linkText: 'Shop now',
  },
];